### ISSUE TITLE
 JCenter's shutdown in February 2021

### ISSUE THREAD

**Issue by mo7ty** [maximeroussy/invitrode#1]
I'm currently using [Invitrode](https://mvnrepository.com/artifact/com.maximeroussy.invitrode/invitrode) for a Mock setup with Java.

As mentioned by Gradle's warning when compiling projects that use this library:

```
The RepositoryHandler.jcenter() method has been deprecated.
This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's shutdown in February 2021.
Use mavenCentral() instead. Consult the upgrading guide for further information:
```
[Upgrading your build from Gradle 6.x to the latest](https://docs.gradle.org/7.1/userguide/upgrading_version_6.html#jcenter_deprecation)

Is it possible to publish it in Maven Central?

**Comment by maximeroussy** [comment]
I can and should certainly do that 👍🏼 
Not sure of exact timelines, but I'll post here when it's done.

**Comment by SanjayDevTech** [comment]
@maximeroussy any update

**Comment by maximeroussy** [comment]
Sorry guys, I started the first steps and then got distracted. 

It should be available from Maven Central now (same latest version), no changes needed for your projects. Give it a try when you get a chance @mo7ty @SanjayDevTech

**Comment by mo7ty** [comment]
Thanks @maximeroussy! 👍 
It's working!
